name: Release
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Build Game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./game/
        cache: true
        archive_output: false

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ steps.tag.outputs.new_tag }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
